[package]
name = "pimostat"
version = "0.1.0"
authors = ["Kai Wohlfahrt <kai.wohlfahrt@gmail.com>"]
build = "build.rs"

[dependencies]
capnp = "0.12"
capnp-rpc = "0.12"
capnp-futures = "0.12"
clap = "2.33"
tokio = "0.2"

[build-dependencies]
capnpc = "0.12"

[lib]
name = "pimostat"
path = "src/lib/lib.rs"

[[bin]]
name = "controller"
path = "src/controller/main.rs"

[[bin]]
name = "sensor"
path = "src/sensor/main.rs"

[[bin]]
name = "actor"
path = "src/actor/main.rs"
