[package]
name = "pimostat"
version = "0.1.0"
authors = ["Kai Wohlfahrt <kai.wohlfahrt@gmail.com>"]
build = "build.rs"

[dependencies]
capnp = "0.9"
capnp-rpc = "0.9"
clap = "2.32"

[build-dependencies]
capnpc = "0.9"

[[bin]]
name = "controller"
path = "src/controller/main.rs"

[[bin]]
name = "sensor"
path = "src/sensor/main.rs"
